QuanLyHopDongVaKySo.CLIENT/Controllers/InstallStaffController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using QuanLyHopDongVaKySo.CLIENT.Constants;
using QuanLyHopDongVaKySo.CLIENT.Helpers;
using QuanLyHopDongVaKySo.CLIENT.Models;
using QuanLyHopDongVaKySo.CLIENT.Models.ModelPut;
using QuanLyHopDongVaKySo.CLIENT.Services.CustomerServices;
using QuanLyHopDongVaKySo.CLIENT.Services.DContractsServices;
using QuanLyHopDongVaKySo.CLIENT.Services.EmployeesServices;
using QuanLyHopDongVaKySo.CLIENT.Services.InstallationDevicesServices;
using QuanLyHopDongVaKySo.CLIENT.Services.IRequirementsServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PasswordServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PFXCertificateServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PMinuteServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PositionServices;
using QuanLyHopDongVaKySo.CLIENT.Services.RoleServices;
using QuanLyHopDongVaKySo.CLIENT.Services.SigningServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TContractServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TMinuteServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TOSServices;
using QuanLyHopDongVaKySo.CLIENT.ViewModels;
using QuanLyHopDongVaKySo_API.Models.ViewPost;
using VMAPI = QuanLyHopDongVaKySo_API.ViewModels;
using Syncfusion.EJ2.Maps;
using System.Drawing.Imaging;
using test.Models;
using API = QuanLyHopDongVaKySo_API.Models; 
using QuanLyHopDongVaKySo.CLIENT.Services.HistoryServices;
using QuanLyHopDongVaKySo.CLIENT.Services.DMinuteServices;

namespace QuanLyHopDongVaKySo.CLIENT.Controllers
{
    public class InstallStaffController : Controller
    {
        private readonly IIRequirementService _iRequirementService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IRoleService _roleService;
        private readonly IPositionService _positionService;
        private readonly IEmployeeService _employeeService;
        private readonly IPFXCertificateServices _pfxCertificateServices;
        private readonly IDContractsService _doneContractSvc;
        private readonly IPMinuteService _pMinuteService;
        private readonly ITOSService _tosService;
        private readonly ITMinuteService _tMinuteService;
        private readonly IInstallationDevicesService _installationDevicesService;
        private readonly ITContractService _tContractService;
        private readonly IUploadHelper _uploadHelper;
        private readonly IPasswordService _passwordService;
        private readonly ICustomerService _customerService;
        private readonly IPdfToImageHelper _pdfToImageHelper;
        private readonly ISigningService _signingService;
        private readonly IHistoryEmpSvc _historyEmpSvc;
        private readonly IHistoryCusSvc _historyCusSvc;
        private readonly IDMinuteService _dMinuteService;


        private int isAuthenticate;
        private string employeeId;

        public int IsAuthenticate
        {
            get
            {
                if (!String.IsNullOrEmpty(HttpContext.Session.GetString(SessionKey.Employee.EmployeeID)))
                {
                    string role = HttpContext.Session.GetString(SessionKey.Employee.Role);
                    if (role == "Admin")
                    {
                      
                        isAuthenticate = 1; //Admin

                    }
                    else if (role == "Giám đốc")
                    {
                       
                        isAuthenticate = 2; //Director
                    }
                    else if (role == "Nhân viên kinh doanh")
                    {
                       
                        isAuthenticate = 3; //BusinessStaff
                    }
                    else if (role == "Nhân viên lắp đặt")
                    {
                      
                        isAuthenticate = 4; //InstallStaff
                    }
                }
                else
                {
                    isAuthenticate = 0; // chưa login
                }
                return isAuthenticate;
            }
            set { this.isAuthenticate = value; }
        }

        public string EmployeeId
        {
            get
            {
                if (!String.IsNullOrEmpty(HttpContext.Session.GetString(SessionKey.Employee.EmployeeID)))
                {
                    employeeId = HttpContext.Session.GetString(SessionKey.Employee.EmployeeID);
                }
                return employeeId;
            }
            set { this.employeeId = value; }
        }

        public InstallStaffController(IIRequirementService iRequirementService, IWebHostEnvironment hostingEnvironment, IHttpContextAccessor contextAccessor, IRoleService roleService,
            IPositionService positionSerivce, IEmployeeService employeeService, IPFXCertificateServices pfxCertificateServices, IDContractsService doneContractSvc,
            IPMinuteService pMinuteService, ITOSService tosService, ITMinuteService tMinuteService, IInstallationDevicesService installationDevicesService, ITContractService tContractService,
            IUploadHelper uploadHelper, IPasswordService passwordService, IPdfToImageHelper pdfToImageHelper, ICustomerService customerService, ISigningService signingService,
            IHistoryEmpSvc historyEmpSvc, IHistoryCusSvc historyCusSvc, IDMinuteService dMinuteService)
        {
            _iRequirementService = iRequirementService;
            _hostingEnvironment = hostingEnvironment;
            _contextAccessor = contextAccessor;
            _roleService = roleService;
            _positionService = positionSerivce;
            _pfxCertificateServices = pfxCertificateServices;
            _employeeService = employeeService;
            _doneContractSvc = doneContractSvc;
            _pMinuteService = pMinuteService;
            _tosService = tosService;
            _tMinuteService = tMinuteService;
            _installationDevicesService = installationDevicesService;
            _tContractService = tContractService;
            _uploadHelper = uploadHelper;
            _passwordService = passwordService;
            _pdfToImageHelper = pdfToImageHelper;
            _customerService = customerService;
            _signingService = signingService;
            _historyEmpSvc = historyEmpSvc;
            _historyCusSvc = historyCusSvc;
            _dMinuteService = dMinuteService;
        }

        public IActionResult ChangePass()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetOTP()
        {
            var respone = await _passwordService.GetOTPChangeAsync(EmployeeId);
            if (respone != null)
            {
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassAction([FromBody] VMAPI.ChangePassword change)
        {
            change.EmployeeID = EmployeeId;
            var respone = await _passwordService.ChangePasswordAsync(change);
            if (respone != null)
            {
                var emp = await _employeeService.GetEmployeePutById(EmployeeId);
                emp.IsFirstLogin = false;
                var respone1 = await _employeeService.UpdateEmployee(emp);
                if (respone1 != null)
                {

                    var empContextDoing = HttpContext.Session.GetString(SessionKey.Employee.EmployeeContext);
                    Employee employeeDoing = JsonConvert.DeserializeObject<Employee>(empContextDoing);
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{employeeDoing.FullName} - ID:{employeeDoing.EmployeeId.ToString().Substring(0, 8)} đã thay đổi mật khẩu cá nhân.",
                        EmployeeID = employeeDoing.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);


                    TempData["SweetType"] = "success";
                    TempData["SweetIcon"] = "success";
                    TempData["SweetTitle"] = $"{employeeDoing.FullName} thay đổi mật khẩu thành công !!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                // mk cũ không đúng
                TempData["SweetType"] = "error";
                TempData["SweetIcon"] = "error";
                TempData["SweetTitle"] = "Mật khẩu cũ không đúng!!";
                return BadRequest();
            }
        }
        public async Task<IActionResult> Record_Install_Pendding()
        {
            if (IsAuthenticate == 1 || IsAuthenticate == 4)
            {
                VMListInstallRecord vm = new VMListInstallRecord()
                {
                    pendingMinutes = await _pMinuteService.GetByEmpId(EmployeeId),
                };
                return View(vm);
            }
            return RedirectToAction("Index", "Verify");
        }
        public async Task<IActionResult> Record_Install_Require()
        {
            VMListIRequire vm = new VMListIRequire();
            if (IsAuthenticate == 1 || IsAuthenticate == 4)
            {
                vm.IRequirements = await _iRequirementService.GetAll();
                return View(vm);
            }
            return RedirectToAction("Index", "Verify");

        }

        public async Task<IActionResult> GetTaskFormIR(int iRequirementID)
        {
            if (IsAuthenticate == 1 || IsAuthenticate == 4)
            {
                PostGetTaskFromIR task = new PostGetTaskFromIR()
                {
                    IRequirementId = iRequirementID,
                    EmployeeID = HttpContext.Session.GetString(SessionKey.Employee.EmployeeID)
                };

QuanLyHopDongVaKySo.CLIENT/Views/InstallStaff/DetailsInstallComplete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@inject IWebHostEnvironment _hostingEnvironment
@model QuanLyHopDongVaKySo.CLIENT.ViewModels.VMDeitalsMinute;
@{
    List<string> imageFilesMinute = new List<string>();
    string fileDMinuteNull = "Resource/Image/empty.png";
    string folderPath = System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "MinuteImage"); // + thêm ID của contract

    string? folderItemMinute = System.IO.Path.Combine(folderPath, Model.DoneMinute.DoneMinuteID.ToString());

    if (folderItemMinute != null)
    {
        imageFilesMinute = Directory.GetFiles(folderItemMinute).ToList();
    }
    string userRole = Context.Request.HttpContext.Session.GetString("Role");
}
<div class="container-fluid">
    @if (userRole == "Admin")
    {
        Layout = "_AdminLayout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Nhân viên lắp đặt</a></li>
                    <li class="breadcrumb-item"><a>Quản lý yêu cầu lắp</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Biên bản đã nhận lắp</li>
                </ol>
            </nav>
            <h1 class="typeHead">CHI TIẾT BIÊN BẢN ĐÃ LẮP</h1>
            <div class="row">
                <a class="col-md-2 button-design" asp-action="Record_Install_Complete" asp-controller="InstallStaff">
                    <i class="ph-bold ph-arrow-left"></i>
                    QUAY LẠI
                </a>
            </div>
        </div>
    }
    else
    {
        Layout = "_Layout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Quản lý yêu cầu lắp</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Biên bản đã nhận lắp</li>
                </ol>
            </nav>
            <h1 class="typeHead">CHI TIẾT BIÊN BẢN LẮP</h1>
            <div class="row">
                <a class="col-md-2 button-design" asp-action="Record_Install_Complete" asp-controller="InstallStaff">
                    <i class="ph-bold ph-arrow-left"></i>
                    QUAY LẠI
                </a>
            </div>
        </div>
    }
    <div class="row bg-white rounded mt-4 mx-auto my-auto">
        <div class="col-6" style="margin: 20px;">
            <div class="showFile">
                <div class="row justify-content-between" style="margin:auto;">
                    <h4 class="col-5 typeHead">Biên bản lắp đặt</h4>
                    <button class="custom-file-upload col-1" data-bs-toggle="modal" data-bs-target="#ShowMinute" style="width:30px; height:30px;">
                        <i class="ph-bold ph-frame-corners" style="font-size:30px; margin: auto;"></i>
                    </button>
                </div>
                <div id="myCarousel1" class="carousel slide" style=" width:100%;height: 750px;">
                    <div class="carousel-inner">
                        <div class="carousel-item active ">
                            <img src="~/Resource/Image/LOGO/1.png" alt="Hình ảnh" width="100%" />
                        </div>
                         @if (folderItemMinute != null)
                        {
                            @foreach (var imgPath in imageFilesMinute)
                            {
                                <div class="carousel-item" style="max-height: 800px;overflow-y: scroll;">
                                    <img src="@Url.Content("~/MinuteImage/"+Model.DoneMinute.DoneMinuteID+"/" + System.IO.Path.GetFileName(imgPath))" alt="Hình ảnh" style="width:100%;" />
                                </div>
                            }
                        }
                        else
                        {
                            <div class="carousel-item" style="max-height: 800px;overflow-y: scroll;">
                                <img src="~/@fileDMinuteNull" alt="Hình ảnh" width="100%" />
                            </div>
                        } 
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel1" data-bs-slide="prev" style="margin: auto;background-color: black;font-size: 100px;width: 50px;height: 100px;">
                        <span class="carousel-control-prev-icon" aria-hidden="true" style="width:20px; height:20px;"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button style="margin: auto;background-color: black;font-size: 100px; width: 50px;height: 100px;" class="carousel-control-next" type="button" data-bs-target="#myCarousel1" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true" style="width:20px; height:20px;"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>

                <!--Show hợp đồng to-->
                <!-- Modal -->
                <div class="modal fade" id="ShowMinute" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div id="myCarouselModal1" class="carousel slide">
                                    <div class="carousel-inner">
                                        <div class="carousel-item active ">
                                            <img src="~/Resource/Image/LOGO/1.png" alt="Hình ảnh" width="100%" />
                                        </div>
                                        @if (folderItemMinute != null)
                                        {
                                            @foreach (var imgPath in imageFilesMinute)
                                            {
                                                <div class="carousel-item" style="max-height: 800px;overflow-y: scroll;">
                                                    <img src="@Url.Content("~/MinuteImage/"+Model.DoneMinute.DoneMinuteID+"/" + System.IO.Path.GetFileName(imgPath))" alt="Hình ảnh" style="width:100%;" />
                                                </div>
                                            }
                                        }
                                       
                                        else
                                        {
                                            <div class="carousel-item" style="max-height: 800px;overflow-y: scroll;">
                                                <img src="~/@fileDMinuteNull" alt="Hình ảnh" width="100%" />
                                            </div>
                                        } 
                                    </div>
                                    <button class="carousel-control-prev" type="button" data-bs-target="#myCarouselModal1" data-bs-slide="prev" style="margin: auto;background-color: black;font-size: 100px;width: 50px;height: 100px;">
                                        <span class="carousel-control-prev-icon" aria-hidden="true" style="width:20px; height:20px;"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button style="margin: auto;background-color: black;font-size: 100px; width: 50px;height: 100px;" class="carousel-control-next" type="button" data-bs-target="#myCarouselModal1" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true" style="width:20px; height:20px;"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="inforCus col-5 mt-4" style="max-height:800px; overflow-y: scroll; ">
            <h4 class="typeHead">
                Thông tin khách hàng
            </h4>
             <form class="row g-3" style="max-width:950px;">
                <div class="col-md-6">
                    <label for="inputName" class="form-label fw-bold">Họ và tên</label>
                    <input type="text" class="form-input" id="inputName" asp-for="@Model.Employee.FullName" readonly>
                </div>
                <div class="col-md-6">
                    <label for="inputState" class="form-label fw-bold">Giới tính</label>
                    @if (Model.Employee.Gender == 1)
                    {
                        <input type="text" class="form-input" id="inputName" readonly value="Nam">
                    }
                    else
                    {
                        <input type="text" class="form-input" id="inputName" readonly value="Nữ">
                    }
                </div>
                <div class="col-md-6">
                    <label for="inputCCCD" class="form-label fw-bold">CCCD/CMND</label>
                    <input type="text" class="form-input" id="inputCCCD" asp-for="@Model.Employee.Identification" readonly>
                </div>
                <div class="col-md-5">
                    <label for="inputPhone" class="form-label fw-bold">Số điện thoại</label>
                    <input type="text" class="form-input" id="inputPhone" asp-for="@Model.Employee.PhoneNumber" readonly>
                </div>
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label fw-bold">Địa chỉ Email</label>
                    <input type="email" class="form-input" id="inputEmail4" asp-for="@Model.Employee.Email" readonly>
                </div>
                <div class="col-md-5">
                    <label for="inputAddress" class="form-label fw-bold">Nơi ở</label>
                    <input type="text" class="form-input" id="inputAddress" asp-for="@Model.Employee.Address" readonly>
                </div>
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label fw-bold">Mã hợp đồng</label>
                    <input type="email" class="form-input" id="inputEmail4"  readonly>
                </div>
                <div class="col-md-5">
                    <label for="inputAddress" class="form-label fw-bold">Loại dịch vụ đã đăng ký</label>
                    <input type="text" class="form-input" id="inputAddress"   readonly>
                </div>
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label fw-bold">Ngày hiệu lực</label>
                    <input type="email" class="form-input" id="inputEmail4"  readonly >
                </div>
                <div class="col-md-5">
                    <label for="inputAddress" class="form-label fw-bold">Mã Biên bản lắp </label>
                    <input type="text" class="form-input" id="inputAddress" readonly>
                </div>
                <h4 class="typeHead mt-3">
                    Thông tin nhân viên lắp đặt
                </h4>
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label fw-bold">Mã nhân viên</label>
                    <input type="email" class="form-input" id="inputEmail4"  asp-for="@Model.Employee.EmployeeId" readonly>
                </div>
                <div class="col-md-5">
                    <label for="inputAddress" class="form-label fw-bold">Họ và tên</label>
                    <input type="text" class="form-input" id="inputAddress"  asp-for="@Model.Employee.FullName" readonly>
                </div>
                <div class="col-md-6">
                    <label for="inputEmail4" class="form-label fw-bold">Email</label>
                    <input type="email" class="form-input" id="inputEmail4" asp-for="@Model.Employee.Email" readonly> 
                </div>
                <div class="col-md-5">
                    <label for="inputAddress" class="form-label fw-bold">Số điện thoại</label>
                    <input type="text" class="form-input" id="inputAddress"  asp-for="@Model.Employee.PhoneNumber" readonly>
                </div>
            </form> 
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#myCarousel1').carousel({
            interval: false
        });
    });
    $(document).ready(function () {
        $('#myCarouselModal1').carousel({
            interval: false
        });
    });
</script>

QuanLyHopDongVaKySo.CLIENT/Views/InstallStaff/ListTypeOfService.cshtml
@model QuanLyHopDongVaKySo.CLIENT.ViewModels.VMListTOS
@{
    string userRole = Context.Request.HttpContext.Session.GetString("Role");
}
<div class="container-fluid">
    @if(userRole == "Admin")
    {
        Layout = "_AdminLayout";

        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Nhân viên lắp đặt</a></li>
                    <li class="breadcrumb-item"><a>Quản lý thiết bị</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Danh sách dịch vụ</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH</h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm biên bản nhận lắp" />
            </div>
        </div>
    }
    else
    {
        Layout = "_Layout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Quản lý thiết bị</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Danh sách dịch vụ</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH</h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm..." />
            </div>
        </div>
    }
    <div class="listTable bg-white mt-3 rounded ">
        <table class="table display" id="myTable">
            <thead>
                <tr style="color: #8B909A;">
                    <th scope="col">ID</th>
                    <th scope="col">NGÀY TẠO</th>
                    <th scope="col">NGÀY CẬP NHẬT</th>
                    <th scope="col">TÊN DỊCH VỤ</th>
                    <th scope="col">GIÁ</th>
                    <th scope="col">ĐƠN VỊ THỜI GIAN</th>
                    <th scope="col">TRẠNG THÁI</th>
                    <th scope="col">HÀNH ĐỘNG</th>
                </tr>
            </thead>
            <tbody class="table-group-divider align-middle">
                @foreach (var item in Model.TypeOfServices)
                {
                    <tr>
                        <td scope="row">@item.TOS_ID</td>
                        <td>
                            @item.DateAdded?.ToString("HH:mm:ss dd/MM/yyyy")
                        </td>
                        <td>
                            @item.DateUpdated?.ToString("HH:mm:ss dd/MM/yyyy")
                        </td>
                        <td>@item.ServiceName</td>
                        <td>@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:c}", item.Price)</td>
                        <td>@item.PerTime</td>
                        <td>
                                @if (item.isHidden)
                                {
                                <div class="d-flex align-items-center">
                                    <div style="width: 5px; height: 5px; background-color: red; border-radius: 50%; margin-right: 10px;"></div>
                                    <span>Đã khoá</span>
                                </div>
                                }
                                else
                                {
                                <div class="d-flex align-items-center">
                                    <div style="width: 5px; height: 5px; background-color: #00C9A7; border-radius: 50%; margin-right: 10px;"></div>
                                    <span>Có thể sử dụng</span>
                                </div>
                                }
                        </td>
                        <td>
                            <a asp-route-tosID="@item.TOS_ID" asp-action="DetailsTypeOfService" asp-controller="InstallStaff">Chi tiết</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        // Khởi tạo DataTable
        $('#myTable').DataTable({
            "searching": false,
            "info": false,
            "lengthMenu": [10, 25, 50, 100],
            "pageLength": 25,
            "language": {
                "decimal": "",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Sau",
                    "previous": "Trước"
                },
                "lengthMenu": "Hiển thị _MENU_ dữ liệu",
                "emptyTable": "Không có dữ liệu"
            }
        });
    });


    // tìm kiếm
    document.addEventListener('DOMContentLoaded', function () {
        // Lấy đối tượng ô tìm kiếm và bảng
        var input = document.getElementById('searchInput');
        var table = document.getElementById('myTable');

        // Thêm sự kiện 'input' cho ô tìm kiếm
        input.addEventListener('input', function () {
            // Gọi hàm filterTable khi người dùng nhập liệu
            filterTable();
        });

        function filterTable() {
            // Lấy giá trị từ ô tìm kiếm và chuyển đổi thành chữ thường
            var filter = input.value.toLowerCase();

            // Lấy tất cả các dòng trong tbody của bảng
            var rows = table.getElementsByTagName('tbody')[0].getElementsByTagName('tr');

            // Lặp qua từng dòng và ẩn hoặc hiển thị dựa trên từ khóa tìm kiếm
            for (var i = 0; i < rows.length; i++) {
                var rowData = rows[i].innerText.toLowerCase();
                if (rowData.includes(filter)) {
                    rows[i].style.display = '';
                } else {
                    rows[i].style.display = 'none';
                }
            }
        }
    });

</script>