QuanLyHopDongVaKySo.CLIENT/Controllers/VerifyController.cs
// Ignore Spelling: auth

using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using QuanLyHopDongVaKySo.CLIENT.Services;
using QuanLyHopDongVaKySo.CLIENT.Services.RoleServices;
using QuanLyHopDongVaKySo.CLIENT.ViewModels;
using QuanLyHopDongVaKySo.CLIENT.Constants;
using QuanLyHopDongVaKySo_API.ViewModels;
using QuanLyHopDongVaKySo.CLIENT.Services.PasswordServices;
using QuanLyHopDongVaKySo.CLIENT.Services.HistoryServices;
using API= QuanLyHopDongVaKySo_API.Models;
using Azure;
using QuanLyHopDongVaKySo.CLIENT.Models;
using RestSharp.Serializers;
using QuanLyHopDongVaKySo.CLIENT.Services.EmployeesServices;

namespace QuanLyHopDongVaKySo.CLIENT.Controllers
{
    public class VerifyController : Controller
    {
        private readonly IAuthServices _authServices;
        private readonly IRoleService _roleService;
        private readonly IPasswordService _passwordService;
        private readonly IHistoryEmpSvc _historyEmpSvc;
        private readonly IEmployeeService _employeeSvc;

        public VerifyController(IAuthServices authServices, IRoleService roleService, IPasswordService passwordService, IHistoryEmpSvc historyEmpSvc, IEmployeeService employeeSvc)
        {
            _authServices = authServices;
            _roleService = roleService;
            _passwordService = passwordService;
            _historyEmpSvc = historyEmpSvc;
            _employeeSvc = employeeSvc;
        }

        public IActionResult Index()
        {
            string role = HttpContext.Session.GetString(SessionKey.Employee.Role);
            if (String.IsNullOrEmpty(role))
            {
                ViewBag.SweetType = TempData["SweetType"];
                ViewBag.SweetIcon = TempData["SweetIcon"];
                ViewBag.SweetTitle = TempData["SweetTitle"];
                return View();
            }
            else
            {
                if (role == "Admin")
                {
                    return RedirectToAction("Index1", "Admin");
                }
                else if (role == "Giám đốc")
                {
                    return RedirectToAction("Index", "Director");
                }
                else if (role == "Nhân viên kinh doanh")
                {
                    return RedirectToAction("Index", "BusinessStaff");
                }
                else
                {
                    return RedirectToAction("Index", "InstallStaff");
                }
            }
        }
      

        public IActionResult ResetPass()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetOTP([FromBody]ForgotPassword forgotPassword)
        {
            var respone = await _passwordService.GetOTPForgotAsync(forgotPassword);
            if (respone != null)
            {
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword([FromBody] string comfirmOTP)
        {
            var respone = await _passwordService.ForgotPasswordAsync(comfirmOTP);
            if (respone != null)
            {
                return Ok();
            }
            return BadRequest();
        }

        public async Task<IActionResult> Login(VMLogin login)
        {
            var result = await _authServices.Login(login);


            if (result != null)
            {
                HttpContext.Session.SetString("token", result);
                var reponse = await _employeeSvc.GetEmployeeByEmail(login.Email);
                HttpContext.Session.SetString(SessionKey.Employee.EmployeeContext,JsonConvert.SerializeObject(reponse));
                HttpContext.Session.SetString(SessionKey.Employee.EmployeeID, reponse.EmployeeId.ToString());
                HttpContext.Session.SetString(SessionKey.Employee.Role, _roleService.GetRoleByIdAsync(reponse.RoleID).Result.RoleName);
                string role = HttpContext.Session.GetString(SessionKey.Employee.Role);
                if (role == "Admin")
                {
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{reponse.FullName} - ID:{reponse.EmployeeId.ToString().Substring(0, 8)} đã đăng nhập vào hệ thống.",
                        EmployeeID = reponse.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);

                  
                    if (reponse.IsFirstLogin)
                    {
                        TempData["SweetType"] = "success";
                        TempData["SweetIcon"] = "success";
                        TempData["SweetTitle"] = $"Đăng nhập {role} thành công... Bạn hãy thay đổi mật khẩu !!";
                        return RedirectToAction("Index1", "Admin");
                    }

                   
                    return RedirectToAction("Index", "Admin");
                }
                else if (role == "Giám đốc")
                {
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{reponse.FullName} - ID:{reponse.EmployeeId.ToString().Substring(0, 8)} đã đăng nhập vào hệ thống.",
                        EmployeeID = reponse.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);

                   
                    if (reponse.IsFirstLogin)
                    {
                        TempData["SweetType"] = "success";
                        TempData["SweetIcon"] = "success";
                        TempData["SweetTitle"] = $"Đăng nhập {role} thành công... Bạn hãy thay đổi mật khẩu !!";

                        return RedirectToAction("ChangePass", "Director");
                    }
                    
                    return RedirectToAction("Index", "Director");
                }
                else if (role =="Nhân viên kinh doanh")
                {
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{reponse.FullName} - ID:{reponse.EmployeeId.ToString().Substring(0, 8)} đã đăng nhập vào hệ thống.",
                        EmployeeID = reponse.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);

                   
                    if (reponse.IsFirstLogin)
                    {
                        TempData["SweetType"] = "success";
                        TempData["SweetIcon"] = "success";
                        TempData["SweetTitle"] = $"Đăng nhập {role} thành công... Bạn hãy thay đổi mật khẩu !!";
                        return RedirectToAction("ChangePass", "BusinessStaff");
                    }

                    return RedirectToAction("Index", "BusinessStaff");
                }
                else
                {
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{reponse.FullName} - ID:{reponse.EmployeeId.ToString().Substring(0, 8)} đã đăng nhập vào hệ thống.",
                        EmployeeID = reponse.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);

              
                    if (reponse.IsFirstLogin)
                    {
                        TempData["SweetType"] = "success";
                        TempData["SweetIcon"] = "success";
                        TempData["SweetTitle"] = $"Đăng nhập {role} thành công... Bạn hãy thay đổi mật khẩu !!";
                        return RedirectToAction("ChangePass", "InstallStaff");
                    }

                    return RedirectToAction("Index", "InstallStaff");
                } 
            }
            else
            {
                TempData["SweetType"] = "error";
                TempData["SweetIcon"] = "error";
                TempData["SweetTitle"] = "Đăng nhập thất bại, kiểm tra lại thông tin đăng nhập !!";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Logout()
        {
            string role = HttpContext.Session.GetString(SessionKey.Employee.Role);
            var empContextDoing = HttpContext.Session.GetString(SessionKey.Employee.EmployeeContext);
            Employee employeeDoing = JsonConvert.DeserializeObject<Employee>(empContextDoing);
            API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
            {
                OperationName = $"{employeeDoing.FullName} - ID:{employeeDoing.EmployeeId.ToString().Substring(0, 8)} đã đăng xuất khỏi hệ thống.",
                EmployeeID = employeeDoing.EmployeeId
            };
            await _historyEmpSvc.AddNew(historyEmp);

            HttpContext.Session.Remove(SessionKey.Employee.EmployeeID);
            HttpContext.Session.Remove(SessionKey.Employee.EmployeeContext);
            HttpContext.Session.Remove(SessionKey.Employee.Role);
            HttpContext.Session.Remove(SessionKey.Customer.CustomerID);
            HttpContext.Session.Remove(SessionKey.Customer.CustomerContext);
            HttpContext.Session.Remove(SessionKey.PFXCertificate.Serial);
            HttpContext.Session.Remove(SessionKey.PedningContract.PContractID);
            HttpContext.Session.Remove(SessionKey.PedningMinute.PMinuteID);
            HttpContext.Session.Remove("token");


            TempData["SweetType"] = "success";
            TempData["SweetIcon"] = "success";
            TempData["SweetTitle"] = $"{role} đã đăng xuất thành công.";
            return RedirectToAction("Index");
        }
    }
}

QuanLyHopDongVaKySo.CLIENT/Views/Verify/Index.cshtml
@model QuanLyHopDongVaKySo.CLIENT.ViewModels.VMLogin
@{
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/2.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- ICONS -->
    <script src="https://unpkg.com/@@phosphor-icons/web"></script>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <style>
        .form_login {
            display: flex;
            height: 100vh;
        }

        .side,
        .banner {
            width: 50%;
            height: 100%;
            justify-content: center;
            align-items: center;
            display: flex;
        }

        .side {
            flex-direction: column;
        }
        /*   .banner{
                    background-color: #9D9D9D;
                } */
        .top img {
            width: 366px;
            height: 366px;
        }

        .form {
            width: 486px;
            height: 520px;
            border-radius: 46px;
            background-color: rgba( 217, 217, 217, 0.3);
        }

        h3 {
            display: flex;
            width: 335px;
            height: 123px;
            flex-direction: column;
            justify-content: center;
            color: #0f172a;
            text-align: center;
            font-family: Montserrat;
            font-size: 48px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
            margin: 0 auto;
            opacity: 0.3;
        }

        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 50%;
            height: 100vh;
            background-color: #9D9D9D;
            z-index: 999;
            opacity: 0.2;
        }

        div[class="mb-3"] {
            max-width: 400px;
            margin: 0 auto;
            color: #0f172a;
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
        }

        div[class="row justify-content-between"] {
            max-width: 400px;
            margin: 0 auto;
            padding-top: 10px;
            align-items: center;
            color: #0f172a;
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
            opacity: 0.3;
        }

        .mb-3 > button {
            width: 400px;
            margin: 0 auto;
            height: 50px;
            margin-top: 10px;
            border-radius: 10px;
            background: #6FB1FC;
            color: #FFFF;
            font-weight: bold;
            border: none;
        }

        .mb-3 > label {
            opacity: 0.3;
        }

        .mb-3 input {
            border-radius: 15px;
            background: #D9D9D9;
            height: 50px;
        }

        .password-container {
            position: relative;
            width: 400px;
            margin: auto;
        }

        .input-container {
            position: relative;
        }

        #password {
            padding-right: 30px; 
        }

        .eye-icon {
            position: absolute;
            top: 50%;
            right: 10px;
            transform: translateY(-50%);
            cursor: pointer;
        }

        #eyeIcon{
            font-size: 25px;
        }
    </style>
    <style>
        .loading {
            position: absolute;
            z-index: 1;
            width: 100%;
            height: 100%;
            display: none;
            align-items: center;
            justify-content: center;
            background-color: transparent;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .loading img {
            width: 7rem;
        }
    </style>
</head>
<body>
  
    <div class="form_login">
        <div class="overlay"></div>
        <div class="banner">
            <img src="~/Resource/Image/Background_Login.png" />
        </div>
        <div class="side">
            <div class="top">
                <img src="~/Resource/Image/LOGO_WITHOUT_BG/2.png" />
            </div>
            <form asp-controller="Verify" asp-action="Login" method="post">
                <div class="form">
                    <h3>ĐĂNG NHẬP</h3>
                    <div class="mb-3">
                        <label for="email" class="form-label">EMAIL</label>
                        <input type="email" class="form-control" id="email" asp-for="Email"  required>
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="mb-3 password-container">
                        <label for="password" class="form-label" style="font-weight:bold;">MẬT KHẨU</label>
                        <div class="input-container">
                            <input type="password" class="form-control" asp-for="Password" id="password" required>
                            <div class="eye-icon" onclick="togglePasswordVisibility()">
                                <i class="ph-bold ph-eye-slash" id="eyeIcon"></i>
                            </div>
                        </div>
                        <span class="text-danger" asp-validation-for="Password"></span>
                    </div>

                    <div class="row justify-content-between">
                        <div class="col-md-6">
                            <div class="form-check">
                                <input onclick="login()" class="form-check-input" type="checkbox" name="rememberMe" id="rememberMe">
                                <label class="form-check-label" for="rememberMe">
                                    Ghi nhớ tôi
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6" style="text-align:end;">
                            <label class="form-label">
                                <a style="text-decoration:none;  color: #0f172a;" href="/Verify/ResetPass">Quên mật khẩu?</a>
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <div class="loading" id="loading">
                            <img src="https://icon-library.com/images/spinner-icon-gif/spinner-icon-gif-10.jpg" alt="loading">
                        </div>
                        <button type="submit" id="submitButton" onclick="Loading()">
                            ĐĂNG NHẬP                    
                        </button>
                    </div>

                </div>
            </form>
        </div>
    </div>

</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>
@if (ViewBag.SweetType != null)
{
    <script>
        Swal.fire({
            icon: '@ViewBag.SweetIcon',
            title: '@ViewBag.SweetTitle',
            showConfirmButton: false,
            timer: 1500
        });
    </script>
}
<script type="text/javascript">
  
     const iconLoading = document.getElementById("loading");

    const showLoading = () => {
        iconLoading.style.display = "flex";
    };

    const hideLoading = () => {
        iconLoading.style.display = "none";
    };

    const Loading = () => {
        showLoading(); // Show loading spinner when the button is clicked

        // You can perform additional logic here before or after the form submission
        // For example, submit the form programmatically
        document.querySelector('form').submit();

        // If you want to prevent the form from submitting immediately, you can remove the form submission line

        // Hide loading spinner after the form submission is complete
        setTimeout(() => {
            hideLoading(); // Hide loading icon after some time (replace this with your actual logic)
        }, 3000);
    };

    function login() {
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;

        var rememberMeCheckbox = document.getElementById('rememberMe');
        var rememberMe = rememberMeCheckbox.checked;

      
        if (rememberMe) {
            localStorage.setItem('savedEmail', email);
            localStorage.setItem('savedPassword', password);
        } else {
           
            localStorage.removeItem('savedEmail');
            localStorage.removeItem('savedPassword');
        }
    }
    window.onload = function () {
        var savedEmail = localStorage.getItem('savedEmail');
        var savedPassword = localStorage.getItem('savedPassword');

        if (savedEmail && savedPassword) {
            document.getElementById('email').value = savedEmail;
            document.getElementById('password').value = savedPassword;
        }
    };


    function togglePasswordVisibility() {
        var passwordInput = document.getElementById("password");
        var eyeIcon = document.getElementById("eyeIcon");

        if (passwordInput.type === "password") {
            passwordInput.type = "text";
            eyeIcon.classList.remove("ph-eye-slash");
            eyeIcon.classList.add("ph-eye");
        } else {
            passwordInput.type = "password";
            eyeIcon.classList.remove("ph-eye");
            eyeIcon.classList.add("ph-eye-slash");
        }
    }
</script>

QuanLyHopDongVaKySo.CLIENT/Views/Verify/ResetPass.cshtml
@model QuanLyHopDongVaKySo_API.ViewModels.ForgotPassword 
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/2.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- ICONS -->
    <script src="https://unpkg.com/@@phosphor-icons/web"></script>
    <style>
        .form_login {
            display: flex;
            height: 100vh;
        }

        .side,
        .banner {
            width: 50%;
            height: 100%;
            justify-content: center;
            align-items: center;
            display: flex;
        }

        .side {
            flex-direction: column;
        }
       
        .top img {
            width: 366px;
            height: 366px;
        }

        .form {
            width: 486px;
            height: 520px;
            border-radius: 46px;
            background-color: rgba( 217, 217, 217, 0.3);
        }

        h3 {
            display: flex;
            height: 123px;
            flex-direction: column;
            justify-content: center;
            color: #0f172a;
            text-align: center;
            font-family: Montserrat;
            font-size: 40px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
            margin: 0 auto;
            opacity: 0.3;
        }

        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 50%;
            height: 100vh;
            background-color: #9D9D9D;
            z-index: 999;
            opacity: 0.2;
        }

        div[class="mb-3"] {
            max-width: 400px;
            margin: 0 auto;
            color: #0f172a;
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
        }

        div[class="row justify-content-between"] {
            max-width: 400px;
            margin: 0 auto;
            padding-top: 10px;
            align-items: center;
            color: #0f172a;
            font-size: 16px;
            font-style: normal;
            font-weight: 700;
            line-height: normal;
            opacity: 0.3;
        }

        div[class="mb-3"] > button {
            width: 400px;
            margin: 0 auto;
            height: 50px;
            margin-top: 10px;
            border-radius: 10px;
            background: #6FB1FC;
            color: #FFFF;
            font-weight: bold;
            border: none;
        }
        div[class="mb-3"] > button > a{
            color: white;
            font-weight: bold;
            text-decoration: none;
        }

        div[class="mb-3"] > label {
            opacity: 0.3;
        }

        div[class="mb-3"] input {
            border-radius: 15px;
            background: #D9D9D9;
            height: 50px;
        }

        .otp-container {
            display: flex;
            justify-content: center;
        }

        .otp-input {
            width: 40px;
            height: 40px;
            margin: 0 5px;
            text-align: center;
            font-size: 18px;
        }

        .col-md-6 a{
             margin: 10px;
             display: flex;
             cursor: pointer ;
             text-decoration:underline;
        }

        .disabled {
            opacity: 0.5;
            pointer-events: none;
        }
    </style>
</head>
<body>
    <div class="form_login">
        <div class="overlay"></div>
        <div class="banner">
            <img src="~/Resource/Image/Background_Login.png" />
        </div>
        <div class="side">
            <div class="top">
                <img src="~/Resource/Image/LOGO_WITHOUT_BG/2.png" />
            </div>
            <form asp-controller="Verify" asp-action="Login" method="post">
                <div class="form">
                    <h3>CẤP LẠI MẬT KHẨU</h3>
                    <div class="mb-3">
                        <label for="formGroupExampleInput" class="form-label">EMAIL</label>
                        <input type="email" class="form-control" id="inputEmail" placeholder="abc@gmail.com" required asp-for="Email">
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="mb-3">
                        <label for="formGroupExampleInput2" class="form-label">MÃ OTP</label>
                        <div class="otp-container">
                            <input id="inputOtp1" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 2)">
                            <input id="inputOtp2" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 3)">
                            <input id="inputOtp3" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 4)">
                            <input id="inputOtp4" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 5)">
                            <input id="inputOtp5" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 6)">
                            <input id="inputOtp6" class="otp-input" type="text" maxlength="1" oninput="handleInput(this, 7)">
                        </div>
                        <script>
                            function handleInput(input, nextInputIndex) {
                                const maxLength = parseInt(input.getAttribute('maxlength'), 10);
                                const inputValue = input.value;

                                if (inputValue.length === maxLength) {
                                    const nextInput = document.querySelector(`.otp-input:nth-child(${nextInputIndex})`);

                                    if (nextInput) {
                                        nextInput.focus();
                                    }
                                } else if (inputValue.length === 0) {
                                    const previousInputIndex = nextInputIndex - 2;
                                    const previousInput = document.querySelector(`.otp-input:nth-child(${previousInputIndex})`);

                                    if (previousInput) {
                                        previousInput.focus();
                                    }
                                }
                            }
                        </script>
                        <span class="text-danger"></span>
                    </div>
                    <div class="row justify-content-around" style="color:cornflowerblue;width: 450px;margin: auto;">
                        <div class="mb-3" style="padding:unset; color: cornflowerblue; cursor:pointer;">
                            <a id="myButton" onclick="handleClick(event)">[Lấy mã OTP]</a>
                        </div>
                    </div>

                    <div class="mb-3">
                        <button onclick="resetPassword()">
                            ĐẶT LẠI MẬT KHẨU
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>
<script>
    let isButtonDisabled = false;

    function handleClick(event) {
        const button = document.getElementById('myButton');
        if (!isButtonDisabled) {
            const countdownSpan = document.createElement('span');
            countdownSpan.className = 'countdown';
            button.appendChild(countdownSpan);

            disableButtonForSeconds(180, countdownSpan);
            button.style.cursor = 'not-allowed';
        }

        event.preventDefault();
        var email = {
                Email: $('#inputEmail').val()
            };
        console.log(JSON.stringify(email));
            $.ajax({
                url: '@Url.Action("GetOTP")',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(email),
                success: function (result) {
                    if (!result.success) {
                        
                    
                    }
                },
                error: function () {
                    console.error('Lỗi khi gửi yêu cầu.');
                }
            });
            
    }
   
    function disableButtonForSeconds(seconds, countdownSpan) {
        isButtonDisabled = true;
        document.getElementById('myButton').classList.add('disabled');

        let secondsRemaining = seconds;

        const countdownInterval = setInterval(() => {
            const minutes = Math.floor(secondsRemaining / 60);
            const remainingSeconds = secondsRemaining % 60;

            if (secondsRemaining <= 0) {
                clearInterval(countdownInterval);
                isButtonDisabled = false;
                document.getElementById('myButton').classList.remove('disabled');
                document.getElementById('myButton').style.cursor = 'pointer';
                countdownSpan.remove();
            } else {
                countdownSpan.textContent = ` (${minutes}p ${remainingSeconds}s)`;
                secondsRemaining--;
            }
        }, 1000);
    }


    function resetPassword() {
        var comfirmOTP =
            $('#inputOtp1').val() +
            $('#inputOtp2').val() +
            $('#inputOtp3').val() +
            $('#inputOtp4').val() +
            $('#inputOtp5').val() +
            $('#inputOtp6').val();

        $.ajax({
            url: '@Url.Action("ResetPassword")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(comfirmOTP),
            success: function (result) {
                if (!result.success) {
                    // Replace alert with SweetAlert success message
                    Swal.fire({
                        icon: 'success',
                        title: 'Mật khẩu mới đã được tạo',
                        text: 'Chúng tôi đã tạo một mật khẩu mới và đang gửi đến email của bạn.',
                        timer: 3000,
                        showConfirmButton: false
                    }).then(function () {
                        var redirectToUrl = '@Url.Action("Index", "Verify")';
                        window.location.href = redirectToUrl;
                    });
                }
            },
            error: function () {
                // Replace alert with SweetAlert error message
                Swal.fire({
                    icon: 'error',
                    title: 'Lỗi khi gửi yêu cầu',
                    text: 'Đã xảy ra lỗi khi gửi yêu cầu. Vui lòng thử lại sau.'
                });
            }
        });
    }


</script>