QuanLyHopDongVaKySo.CLIENT/Controllers/BusinessStaffController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using QuanLyHopDongVaKySo.CLIENT.Constants;
using QuanLyHopDongVaKySo.CLIENT.Helpers;
using QuanLyHopDongVaKySo.CLIENT.Models.ModelPost;
using QuanLyHopDongVaKySo.CLIENT.Models.ModelPut;
using QuanLyHopDongVaKySo.CLIENT.Services.CustomerServices;
using QuanLyHopDongVaKySo.CLIENT.Services.DContractsServices;
using QuanLyHopDongVaKySo.CLIENT.Services.EmployeesServices;
using QuanLyHopDongVaKySo.CLIENT.Services.HistoryServices;
using QuanLyHopDongVaKySo.CLIENT.Services.InstallationDevicesServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PasswordServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PContractServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PFXCertificateServices;
using QuanLyHopDongVaKySo.CLIENT.Services.PositionServices;
using QuanLyHopDongVaKySo.CLIENT.Services.RoleServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TContractServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TMinuteServices;
using QuanLyHopDongVaKySo.CLIENT.Services.TOSServices;
using QuanLyHopDongVaKySo.CLIENT.ViewModels;
using QuanLyHopDongVaKySo_API.Models;
using QuanLyHopDongVaKySo_API.ViewModels;
using Spire.Pdf.Graphics;
using System.Drawing.Imaging;
using test.Models;

using API = QuanLyHopDongVaKySo_API.Models;

using Employee = QuanLyHopDongVaKySo_API.Models.Employee;

namespace QuanLyHopDongVaKySo.CLIENT.Controllers
{
    public class BusinessStaffController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IDContractsService _dContractService;
        private readonly IPContractService _pContractService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IEmployeeService _employeeService;
        private readonly ITContractService _tContractService;
        private readonly ITOSService _tosService;
        private readonly ITMinuteService _tMinuteService;
        private readonly IInstallationDevicesService _installationDevicesService;
        private readonly IPFXCertificateServices _pfxCertificateServices;
        private readonly IRoleService _roleService;
        private readonly IPositionService _positionService;
        private readonly IUploadHelper _uploadHelper;
        private readonly IPdfToImageHelper _pdfToImageHelper;
        private readonly IPasswordService _passwordService;
        private readonly IHistoryEmpSvc _historyEmpSvc;


        private int isAuthenticate = 0;
        private string employeeId;

        public int IsAuthenticate
        {
            get
            {
                if (!String.IsNullOrEmpty(HttpContext.Session.GetString(SessionKey.Employee.EmployeeID)))
                {
                    string role = HttpContext.Session.GetString(SessionKey.Employee.Role);
                    TempData["Role"] = role;
                    if (role == "Admin")
                    {
                   
                        isAuthenticate = 1; //Admin

                    }
                    else if (role == "Giám đốc")
                    {
                       
                        isAuthenticate = 2; //Director
                    }
                    else if (role == "Nhân viên kinh doanh")
                    {
                    
                        isAuthenticate = 3; //BusinessStaff
                    }
                    else if (role == "Nhân viên lắp đặt")
                    {
                       
                        isAuthenticate = 4; //InstallStaff
                    }
                }
                else
                {
                    isAuthenticate = 0; // chưa login
                }
                return isAuthenticate;
            }
            set { this.isAuthenticate = value; }
        }
        
        public string EmployeeId
        {
            get
            {
                if (!String.IsNullOrEmpty(HttpContext.Session.GetString(SessionKey.Employee.EmployeeID)))
                {
                    employeeId = HttpContext.Session.GetString(SessionKey.Employee.EmployeeID);
                }
                return employeeId;
            }
            set { this.employeeId = value; }
        }

        public BusinessStaffController(ICustomerService customerService, IDContractsService dContractService, IEmployeeService employeeService,
            IPContractService pContractService, IWebHostEnvironment hostingEnvironment, IHttpContextAccessor contextAccessor, ITContractService tContractService,
            ITOSService tosService, ITMinuteService tMinuteService, IInstallationDevicesService installationDevicesService, IPFXCertificateServices pfxCertificateServices,
            IRoleService roleService, IPositionService positionSerivce, IUploadHelper uploadHelper, IPdfToImageHelper pdfToImageHelper, IPasswordService passwordService,
            IHistoryEmpSvc historyEmpSvc)
        {
            _customerService = customerService;
            _dContractService = dContractService;
            _pContractService = pContractService;
            _hostingEnvironment = hostingEnvironment;
            _contextAccessor = contextAccessor;
            _employeeService = employeeService;
            _tContractService = tContractService;
            _tosService = tosService;
            _roleService = roleService;
            _positionService = positionSerivce;
            _tMinuteService = tMinuteService;
            _installationDevicesService = installationDevicesService;
            _pfxCertificateServices = pfxCertificateServices;
            _uploadHelper = uploadHelper;
            _pdfToImageHelper = pdfToImageHelper;
            _passwordService = passwordService;
            _historyEmpSvc = historyEmpSvc;
        }

        public IActionResult ChangePass()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetOTP()
        {
            var respone = await _passwordService.GetOTPChangeAsync(EmployeeId);
            if (respone != null)
            {
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassAction([FromBody] ChangePassword change)
        {
            if (IsAuthenticate != 3 && IsAuthenticate != 1) { return RedirectToAction("Index", "Verify"); }
            change.EmployeeID = EmployeeId;
            var respone = await _passwordService.ChangePasswordAsync(change);
            if (respone != null)
            {
                var emp = await _employeeService.GetEmployeePutById(EmployeeId);
                emp.IsFirstLogin = false;
                var respone1 = await _employeeService.UpdateEmployee(emp);
                if (respone1 != null)
                {
                    var empContextDoing = HttpContext.Session.GetString(SessionKey.Employee.EmployeeContext);
                    Employee employeeDoing = JsonConvert.DeserializeObject<Employee>(empContextDoing);
                    API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                    {
                        OperationName = $"{employeeDoing.FullName} - ID:{employeeDoing.EmployeeId.ToString().Substring(0, 8)} đã thay đổi mật khẩu cá nhân.",
                        EmployeeID = employeeDoing.EmployeeId
                    };
                    await _historyEmpSvc.AddNew(historyEmp);


                    TempData["SweetType"] = "success";
                    TempData["SweetIcon"] = "success";
                    TempData["SweetTitle"] = $"{employeeDoing.FullName} thay đổi mật khẩu thành công !!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                // mk cũ không đúng
                TempData["SweetType"] = "error";
                TempData["SweetIcon"] = "error";
                TempData["SweetTitle"] = "Mật khẩu cũ không đúng!!";
                return BadRequest();
            }
        }

        public async Task<IActionResult> CreatePContract(VMCreateFormForCus vm)
        {
            if (IsAuthenticate != 3 && IsAuthenticate != 1) { return RedirectToAction("Index", "Verify"); }
            PostPendingContract pContract = new PostPendingContract();
            pContract = vm.PostPendingContract;
            pContract.CustomerId = Guid.Parse(HttpContext.Session.GetString(SessionKey.Customer.CustomerID));
            pContract.EmployeeCreatedId = Guid.Parse(HttpContext.Session.GetString(SessionKey.Employee.EmployeeID));

            var respone = await _pContractService.addAsnyc(pContract);
            
            if (respone != null)
            {
                string[] split = respone.Split('*');
                string pdfPath = null;
                IFormFile file = _uploadHelper.ConvertBase64ToIFormFile(split[0], Guid.NewGuid().ToString().Substring(0, 8), "application/pdf");
                pdfPath = _uploadHelper.UploadPDF(file, _hostingEnvironment.WebRootPath, "TempFile", ".pdf");
                _pdfToImageHelper.PdfToPng(pdfPath, int.Parse(split[1]), "pcontract");

                System.GC.Collect();
                System.GC.WaitForPendingFinalizers();
                System.IO.File.Delete(pdfPath);

                var empContextDoing = HttpContext.Session.GetString(SessionKey.Employee.EmployeeContext);
                Employee employeeDoing = JsonConvert.DeserializeObject<Employee>(empContextDoing);
                var customer = await _customerService.GetCustomerById(pContract.CustomerId.ToString());
                API.OperationHistoryEmp historyEmp = new API.OperationHistoryEmp()
                {

QuanLyHopDongVaKySo.CLIENT/Views/BusinessStaff/ContractFormPage.cshtml
@model QuanLyHopDongVaKySo_API.Models.PostTContract
@{
    string userRole = Context.Request.HttpContext.Session.GetString("Role");
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
<style>
    #loading-spinner {
        display: none;
        z-index: 1;
        width: 100%;
        height: 100%;
        align-items: center;
        justify-content: center;
        background-color: transparent;
        position: fixed;
        top: 100%;
        left: 100%;
        transform: translate(-50%, -50%);
    }

        #loading-spinner > img {
            width: 10rem;
        }
</style>

<div class="container-fluid">
    @if (userRole == "Admin")
    {
        Layout = "_AdminLayout";

        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex rounded">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"> <a>Nhân viên kinh doanh</a></li>
                    <li class="breadcrumb-item"> <a>Hợp đồng - Biên bản mẫu</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Thêm mẫu hợp đồng</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẢI HỢP ĐỒNG MẪU</h1>
        </div>
    }
    else
    {
        <link href="~/php/style.css" rel="stylesheet" />
        Layout = "_Layout";

        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Hợp đồng - Biên bản mẫu</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Thêm mẫu hợp đồng</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẢI HỢP ĐỒNG MẪU</h1>
        </div>
    }
    <div class="row mt-4 mx-auto">
            <form class="form" method="post" enctype="multipart/form-data" id="FormPostTContract" asp-action="AddTContract" asp-controller="BusinessStaff">
                <input asp-for="File" type="file" accept=".pdf" id="pdfInput" style="display:none;" required>
                <img width="64" height="64" style="margin-bottom:15px" src="~/Images/pdf_icon.png" alt="external-pdf-file-types-others-iconmarket" />
                <button type="button" class="button-22" id="uploadIcon">TẢI PDF</button>
                <br />
                <section>
                    <div style="display: flex; justify-content: space-evenly;">
                    <button type="submit" class="button-22" id="saveButton" style="display:none;" onclick="saveData()">
                            Lưu
                       
                        </button>
                    </div>
                </section>
            </form>
    </div>
    <div id="loading-spinner">
        <img src="https://icon-library.com/images/spinner-icon-gif/spinner-icon-gif-10.jpg" alt="loading">
    </div>
</div>


<script type="text/javascript">
    document.getElementById('uploadIcon').addEventListener('click', function () {
        document.getElementById('pdfInput').click();
    });

    function saveData() {
        event.preventDefault();
        document.getElementById('loading-spinner').style.display = 'block';
        document.getElementById("FormPostTContract").submit();
    }

    document.getElementById('pdfInput').addEventListener('change', function () {
        var fileInput = document.getElementById('pdfInput');
        var saveButton = document.getElementById('saveButton');

        if (fileInput.files.length > 0) {
            var uploadedFileName = fileInput.files[0].name;

            // Show loading before processing
            showLoading();

            setTimeout(function () {
                showSuccessAlert(uploadedFileName);
                saveButton.style.display = 'block';
                // Hide loading after successful processing
                hideLoading();
            }, 2000);
        } else {
            setTimeout(function () {
                showErrorAlert(uploadedFileName);
                saveButton.style.display = 'none';
                // Hide loading after processing (whether successful or not)
                hideLoading();
            }, 2000);
        }
    });

    function showSuccessAlert(uploadedFileName) {
        // Hiển thị SweetAlert với thông báo thành công và tên tệp
        Swal.fire({
            icon: 'success',
            title: 'Thành công!',
            text: 'Tệp ' + uploadedFileName + ' đã được chọn thành công.',
            confirmButtonText: 'OK'
        });
    }


    function showErrorAlert(uploadedFileName) {
        // Hiển thị SweetAlert với thông báo không thành công
        Swal.fire({
            icon: 'error',
            title: 'Không thành công!',
            text: 'Lưu tệp ' + uploadedFileName + 'không thành công',
            confirmButtonText: 'OK'
        });
    }
 
</script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>

QuanLyHopDongVaKySo.CLIENT/Views/BusinessStaff/Contracts_Approved.cshtml
@model List<QuanLyHopDongVaKySo_API.ViewModels.DContractViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string userRole = Context.Request.HttpContext.Session.GetString("Role");
}
<div class="container-fluid">
    @if(userRole == "Admin")
    {
        Layout = "_AdminLayout";

        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"> <a>Nhân viên kinh doanh</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Hợp đồng đã hoành thành</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH </h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm hợp đồng hoàn thành" />
            </div>
        </div>

    }
    else
    {
        Layout = "_Layout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page"> Hợp đồng đã hoàn thành</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH </h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm hợp đồng hoàn thành" />
            </div>
        </div>

    }
    <div class="row bg-white mx-auto my-auto mt-4 rounded">
        <div class="listTable">
            <table class="table display" id="myTable">
                <thead>
                    <tr style="color: #8B909A;">
                        <th scope="col">ID</th>
                        <th scope="col">EMAIL</th>
                        <th scope="col">NGÀY ĐĂNG KÝ DỊCH VỤ</th>
                        <th scope="col">HỌ VÀ TÊN</th>
                        <th scope="col">LOẠI HỢP ĐỒNG ĐĂNG KÝ</th>
                        <th scope="col">TRẠNG THÁI</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.Id </th>
                            <td>@item.CustomerEmail</td>
                            <td>@item.DateDone</td>
                            <td>@item.CustomerName</td>
                            <td>@item.TypeOfService</td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div style="width: 5px; height: 5px; background-color: #00C9A7; border-radius: 50%; margin-right: 10px;"></div>
                                    <span>@item.Status</span>
                                </div>
                            </td>
                            <td>
                                <a asp-controller="BusinessStaff" asp-action="Details_Contract_Approved" asp-route-id="@item.Id">Chi tiết</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        // Khởi tạo DataTable
        $('#myTable').DataTable({
            "searching": false,
            "info": false,
            "lengthMenu": [10, 25, 50, 100],
            "pageLength": 25,
            "language": {
                "decimal": "",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Sau",
                    "previous": "Trước"
                },
                "lengthMenu": "Hiển thị _MENU_ dữ liệu",
                "emptyTable": "Không có dữ liệu"
            }
            }
        });
    });
    // tìm kiếm
    document.addEventListener('DOMContentLoaded', function () {
        // Lấy đối tượng ô tìm kiếm và bảng
        var input = document.getElementById('searchInput');
        var table = document.getElementById('myTable');

        // Thêm sự kiện 'input' cho ô tìm kiếm
        input.addEventListener('input', function () {
            // Gọi hàm filterTable khi người dùng nhập liệu
            filterTable();
        });

        function filterTable() {
            // Lấy giá trị từ ô tìm kiếm và chuyển đổi thành chữ thường
            var filter = input.value.toLowerCase();

            // Lấy tất cả các dòng trong tbody của bảng
            var rows = table.getElementsByTagName('tbody')[0].getElementsByTagName('tr');

            // Lặp qua từng dòng và ẩn hoặc hiển thị dựa trên từ khóa tìm kiếm
            for (var i = 0; i < rows.length; i++) {
                var rowData = rows[i].innerText.toLowerCase();
                if (rowData.includes(filter)) {
                    rows[i].style.display = '';
                } else {
                    rows[i].style.display = 'none';
                }
            }
        }
    });
</script>

QuanLyHopDongVaKySo.CLIENT/Views/BusinessStaff/Contracts_PendingApproval.cshtml
@model List<QuanLyHopDongVaKySo_API.ViewModels.PContractViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string userRole = Context.Request.HttpContext.Session.GetString("Role");
}
<div class="container-fluid">
    @if (userRole == "Admin")
    {
        Layout = "_AdminLayout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"> <a>Nhân viên kinh doanh</a></li>
                    <li class="breadcrumb-item"><a>Quản lý hợp đồng</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewData["Tille"]</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH</h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm" />
            </div>
        </div>
    }
    else
    {
        Layout = "_Layout";
        <div class=" block justify-between items-center p-4  mt-4 mb-6 bg-white rounded-2xl shadow-xl shadow-gray-200 lg:p-5 sm:flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <i class="ph-bold ph-house" style="font-size: 20px; margin: auto 5px;"></i>
                    <li class="breadcrumb-item"> <a>Trang chủ</a></li>
                    <li class="breadcrumb-item"><a>Quản lý hợp đồng</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewData["Tille"]</li>
                </ol>
            </nav>
            <h1 class="typeHead">TẤT CẢ DANH SÁCH</h1>
            <div class="row">
                <input type="search" id="searchInput" style="margin-left: 10px;" placeholder="Tìm kiếm" />
            </div>
        </div>
    }
    <div class="row bg-white mx-auto mt-4 rounded">
        <div class="listTable">
            <table class="table display" id="myTable">
                <thead>
                    <tr style="color: #8B909A;">
                        <th scope="col">ID</th>
                        <th scope="col">EMAIL</th>
                        <th scope="col">NGÀY ĐĂNG KÝ DỊCH VỤ</th>
                        <th scope="col">HỌ VÀ TÊN</th>
                        <th scope="col">LOẠI HỢP ĐỒNG ĐĂNG KÝ</th>
                        <th scope="col">TRẠNG THÁI</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody class="table-group-divider align-middle">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@item.PContractID</th>
                            <td>@item.CustomerEmail</td>
                            <td>@item.DateCreated</td>
                            <td>@item.CustomerName</td>
                            <td>@item.TOS_ID</td>
                            <td>
                                @if (item.IsRefuse == "Từ chối")
                                {
                                    <div class="d-flex align-items-center">
                                        <div style="width: 5px; height: 5px; background-color: #FF000F; border-radius: 50%; margin-right: 10px;"></div>
                                        <span> @item.IsRefuse</span>
                                    </div>
                                }
                                else if (item.IsDirector == "Chờ ký" || item.IsCustomer == "Chờ ký")
                                {
                                    <div class="d-flex align-items-center">
                                        <div style="width: 5px; height: 5px; background-color: #FFCA2C; border-radius: 50%; margin-right: 10px;"></div>
                                        <span>Chờ ký</span>
                                    </div>
                                }
                            </td>
                            <td>
                                <a asp-action="Details_Contract_PendingApproved" asp-controller="BusinessStaff" asp-route-id="@item.PContractID" asp-route-tille="@ViewData["Tille"]" asp-route-viewBack="@ViewData["ViewBack"]">Chi tiết</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        // Khởi tạo DataTable
        $('#myTable').DataTable({
            "searching": false,
            "info": false,
            "lengthMenu": [10, 25, 50, 100],
            "pageLength": 25,
            "language": {
                "decimal": "",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Sau",
                    "previous": "Trước"
                },
                "lengthMenu": "Hiển thị _MENU_ dữ liệu",
                "emptyTable": "Không có dữ liệu"
            }
        });
    });

    // tìm kiếm
    document.addEventListener('DOMContentLoaded', function () {
        // Lấy đối tượng ô tìm kiếm và bảng
        var input = document.getElementById('searchInput');
        var table = document.getElementById('myTable');

        // Thêm sự kiện 'input' cho ô tìm kiếm
        input.addEventListener('input', function () {
            // Gọi hàm filterTable khi người dùng nhập liệu
            filterTable();
        });

        function filterTable() {
            // Lấy giá trị từ ô tìm kiếm và chuyển đổi thành chữ thường
            var filter = input.value.toLowerCase();

            // Lấy tất cả các dòng trong tbody của bảng
            var rows = table.getElementsByTagName('tbody')[0].getElementsByTagName('tr');

            // Lặp qua từng dòng và ẩn hoặc hiển thị dựa trên từ khóa tìm kiếm
            for (var i = 0; i < rows.length; i++) {
                var rowData = rows[i].innerText.toLowerCase();
                if (rowData.includes(filter)) {
                    rows[i].style.display = '';
                } else {
                    rows[i].style.display = 'none';
                }
            }
        }
    });
</script>